# -*- coding: utf-8 -*-
"""PROYECTO-3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BQyQHYOUQ4fNUYY4kg0zesdEQUQPm6XV

# Proyecto: EduPredict - Detección de estudiantes con riesgo de deserción

## Objetivo General

Este proyecto busca actuar como una consultora de Inteligencia Artificial para:
*   Analizar datos
*   Entrenar modelos de Machine Learning
*   Obtener conclusiones
*   Construir visualizaciones
*   Presentar resultados en formato ejecutivo

### Reto Exclusivo — Equipo 3 — EduPredict

**Problema**: Detectar estudiantes con riesgo de deserción.

**Dataset**: `edupredict.csv` (simulado en este notebook)

**Variables del Dataset**:
*   `Promedio`
*   `Fallas`
*   `Horas_Estudio`
*   `Internet` (Si/No)
*   `Trabaja` (Si/No)
*   `Deserta` (Target: 1 para deserción, 0 para no deserción)

**Objetivo**: Clasificación.

**KPI Ejecutivo**: Reducir deserción académica.

**Gráficos sugeridos**:
*   Promedio vs Deserción
*   Fallas vs Deserción
*   Accuracy del modelo

## 1. Carga y Preprocesamiento de Datos

Primero, cargaremos el dataset simulado y realizaremos el preprocesamiento necesario, como la codificación de variables categóricas.
"""

# Importamos las librerías necesarias
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import cross_val_score
import numpy as np

# Dataset simulado (edupredict.csv)
data = {
    "Promedio": [2.5,3.8,4.2,2.8,3.6,2.7,4.5,3.1,4.0,2.4],
    "Fallas": [18,4,1,15,5,17,0,10,2,20],
    "Horas_Estudio": [1,5,6,1,4,1,7,2,5,0],
    "Internet": ["No","Si","Si","No","Si","No","Si","Si","Si","No"],
    "Trabaja": ["Si","No","No","Si","No","Si","No","Si","No","Si"],
    "Deserta": [1,0,0,1,0,1,0,1,0,1]
}

df = pd.DataFrame(data)

print("Dataset original:")
display(df)

# Procesamiento de datos: Codificación de variables categóricas
le = LabelEncoder()
df["Internet"] = le.fit_transform(df["Internet"])
df["Trabaja"] = le.fit_transform(df["Trabaja"])

print("\nDataset después de la codificación (Internet: No=0, Si=1; Trabaja: No=0, Si=1):")
display(df)

"""## 2. Preparación para el Modelo de Machine Learning

Dividimos los datos en variables predictoras (X) y la variable objetivo (y), y luego separamos en conjuntos de entrenamiento y prueba.
"""

# Variables predictoras (X) y variable objetivo (y)
X = df.drop("Deserta", axis=1)
y = df["Deserta"]

# Dividir los datos en conjuntos de entrenamiento y prueba (70% entrenamiento, 30% prueba)
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    random_state=42 # Para reproducibilidad de los resultados
)

print("Dimensiones de X_train:", X_train.shape)
print("Dimensiones de X_test:", X_test.shape)
print("Dimensiones de y_train:", y_train.shape)
print("Dimensiones de y_test:", y_test.shape)

"""## 3. Entrenamiento y Evaluación del Modelo de Árbol de Decisión

Utilizaremos un `DecisionTreeClassifier` para clasificar a los estudiantes y evaluaremos su rendimiento.
"""

# Entrenar el modelo de Árbol de Decisión
modelo = DecisionTreeClassifier(random_state=42)
modelo.fit(X_train, y_train)

# Realizar predicciones sobre el conjunto de prueba
y_pred = modelo.predict(X_test)

print("Predicciones del modelo en el conjunto de prueba:", y_pred)

# Evaluación del modelo
accuracy = accuracy_score(y_test, y_pred)
print(f"\nAccuracy del modelo en el conjunto de prueba: {accuracy:.2f}")

print("\nReporte de Clasificación:")
print(classification_report(y_test, y_pred))

# Matriz de Confusión
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6, 4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['No Deserta', 'Deserta'], yticklabels=['No Deserta', 'Deserta'])
plt.title("Matriz de Confusión")
plt.xlabel("Predicción")
plt.ylabel("Real")
plt.show()

"""## 4. Evaluación del Modelo con Validación Cruzada

El 100% de `accuracy` en el conjunto de prueba, especialmente con un dataset tan pequeño, puede indicar **sobreajuste** (`overfitting`). Para obtener una evaluación más fiable y robusta, es crucial utilizar la **validación cruzada**.
"""

# Evaluación del Modelo de Árbol de Decisión con Validación Cruzada

# Creamos una nueva instancia del modelo para la validación cruzada (asegurando un estado limpio)
modelo_dt_cv = DecisionTreeClassifier(random_state=42)

# Realizamos la validación cruzada (usando 5 'folds' o divisiones)
cv_scores_dt = cross_val_score(modelo_dt_cv, X, y, cv=5, scoring='accuracy')

print(f"Accuracy en cada fold de validación cruzada: {cv_scores_dt}")
print(f"Accuracy promedio (más robusto): {np.mean(cv_scores_dt):.4f}")
print(f"Desviación estándar de los scores: {np.std(cv_scores_dt):.4f}")

# Interpretación:
# Un accuracy promedio cercano a 1.00 con una desviación estándar baja indica un modelo consistente.
# Si el promedio es significativamente menor que el accuracy del conjunto de prueba, puede indicar sobreajuste.

"""## 5. Visualizaciones Sugeridas

Generamos los gráficos solicitados para una mejor comprensión de las relaciones en los datos y el rendimiento del modelo.
"""

# Gráfico 1: Promedio vs Deserción
plt.figure(figsize=(8, 5))
sns.scatterplot(
    data=df,
    x="Promedio",
    y="Deserta",
    hue="Deserta", # Colorear los puntos según la categoría 'Deserta'
    s=150,        # Tamaño de los puntos
    palette='coolwarm' # Paleta de colores
)
plt.title("Promedio vs Deserción")
plt.xlabel("Promedio del Estudiante")
plt.ylabel("Deserción (0=No Deserta, 1=Deserta)")
plt.yticks([0, 1], ['No Deserta', 'Deserta'])
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

# Gráfico 2: Fallas vs Deserción
plt.figure(figsize=(8, 5))
sns.scatterplot(
    data=df,
    x="Fallas",
    y="Deserta",
    hue="Deserta",
    s=150,
    palette='viridis'
)
plt.title("Fallas vs Deserción")
plt.xlabel("Número de Fallas")
plt.ylabel("Deserción (0=No Deserta, 1=Deserta)")
plt.yticks([0, 1], ['No Deserta', 'Deserta'])
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

# Gráfico 3: Accuracy del Modelo (en el conjunto de prueba)
plt.figure(figsize=(6, 4))
plt.bar(["Accuracy en Prueba"], [accuracy], color="skyblue")
plt.ylim(0, 1.1) # Rango del eje Y de 0 a 1.1 para visualizar mejor el 1.0
plt.title("Accuracy del Modelo (Conjunto de Prueba)")
plt.ylabel("Accuracy")
plt.text(0, accuracy + 0.05, f'{accuracy:.2f}', ha='center', va='bottom', fontsize=12)
plt.show()

# Gráfico Adicional: Accuracy Promedio con Validación Cruzada
plt.figure(figsize=(6, 4))
plt.bar(["Accuracy Promedio (CV)"], [np.mean(cv_scores_dt)], color="lightcoral")
plt.ylim(0, 1.1)
plt.title("Accuracy Promedio del Modelo (Validación Cruzada)")
plt.ylabel("Accuracy")
plt.text(0, np.mean(cv_scores_dt) + 0.05, f'{np.mean(cv_scores_dt):.2f}', ha='center', va='bottom', fontsize=12)
plt.show()

"""## 6. Conclusiones Ejecutivas

Este modelo de clasificación demuestra una alta capacidad para identificar a estudiantes en riesgo de deserción basado en los datos proporcionados. La validación cruzada confirma una consistencia en el rendimiento del modelo, aunque se debe tener precaución con el tamaño reducido del dataset.

**Recomendaciones:**
*   **Monitoreo Continuo:** Implementar este modelo para identificar tempranamente a estudiantes en riesgo.
*   **Intervenciones Personalizadas:** Desarrollar programas de apoyo dirigidos a estudiantes identificados con alto riesgo.
*   **Recopilación de Datos Adicionales:** Explorar la inclusión de más variables (e.g., asistencia a clases, participación en actividades, situación socioeconómica) para mejorar la robustez y precisión del modelo.

## Recursos

## 7. Comparación de Modelos y Uso de Pipelines

Para mejorar la robustez y explorar un modelo más complejo, vamos a implementar y comparar un `RandomForestClassifier` con nuestro `DecisionTreeClassifier` inicial. También demostraremos cómo se puede encapsular esto en un `Pipeline`.
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline

# Pipeline para Decision Tree
pipeline_dt = Pipeline([
    ('classifier', DecisionTreeClassifier(random_state=42))
])

# Pipeline para Random Forest
pipeline_rf = Pipeline([
    ('classifier', RandomForestClassifier(random_state=42))
])

# Entrenar ambos pipelines
pipeline_dt.fit(X_train, y_train)
pipeline_rf.fit(X_train, y_train)

# Realizar predicciones
y_pred_dt = pipeline_dt.predict(X_test)
y_pred_rf = pipeline_rf.predict(X_test)

# Evaluar Accuracy
accuracy_dt = accuracy_score(y_test, y_pred_dt)
accuracy_rf = accuracy_score(y_test, y_pred_rf)

print(f"Accuracy (Decision Tree): {accuracy_dt:.2f}")
print(f"Accuracy (Random Forest): {accuracy_rf:.2f}")

"""### Validación Cruzada para Modelos Comparados

Ahora, realizaremos validación cruzada para ambos modelos para obtener una medida más robusta de su rendimiento.
"""

# Validación Cruzada para Decision Tree
cv_scores_dt_pipeline = cross_val_score(pipeline_dt, X, y, cv=5, scoring='accuracy')

# Validación Cruzada para Random Forest
cv_scores_rf_pipeline = cross_val_score(pipeline_rf, X, y, cv=5, scoring='accuracy')

print(f"Accuracy CV (Decision Tree): {cv_scores_dt_pipeline}")
print(f"Accuracy promedio CV (Decision Tree): {np.mean(cv_scores_dt_pipeline):.4f}")
print(f"Desviación estándar CV (Decision Tree): {np.std(cv_scores_dt_pipeline):.4f}")

print(f"\nAccuracy CV (Random Forest): {cv_scores_rf_pipeline}")
print(f"Accuracy promedio CV (Random Forest): {np.mean(cv_scores_rf_pipeline):.4f}")
print(f"Desviación estándar CV (Random Forest): {np.std(cv_scores_rf_pipeline):.4f}")